### ISSUE TITLE
Prototype typechecker and compiler

### ISSUE THREAD

**Issue by MxmUrw** [kami-language/kami#1]
### Todo's

 - [ ] Define simply typed MTT +`leteval`
 - [ ] Define endpoint projection target (as MTT with one-sided `leteval`s), let's call this PMTT
 - [ ] Give a translation of PMTT into erlang/elixir
 - [ ] Give a translation of PMTT into rust
 - [ ] Build a parser to parse MTT terms with type annotations
 - [ ] Build typechecker
